### ISSUE TITLE
This looks very much like what I am looking for 

### ISSUE THREAD

**Issue by LarsBuur** [maxko87/meteor-mongo-graph#4]
Any hints on how to get started with a bare minimum of some data would be very much appreciated. 

Best regards,
Lars Buur

**Comment by maxko87** [comment]
Hey Lars,

Does the README help at all? There should be a couple examples there.

**Comment by LarsBuur** [comment]
It does - however coffee script is not my thing - but I converted it into Javascript! I think whats needed is an simple demo-dataset so I could get it up an running and then explore the possibilities.
